### ISSUE TITLE
Is there any reason to hand-unwraping paths instead of using `fs::canonicalize`

### ISSUE THREAD

**Issue by roman-holovin** [cloudhead/rx#34]
I have tried to use `~`, `..` in paths and `rx` is failing to parse those. Also, I suppose it may fail with symlinks also.

https://github.com/cloudhead/rx/blob/75a11ff3667d035a3b673c908ee4409c7dc92d7b/src/parser.rs#L218

There is [canonicalize](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) function that should be able to resolve paths more reliably.

**Comment by cloudhead** [comment]
As far as I know, `canonicalize` doesn't handle `~`, since that is a shell feature. But for relative paths we should be using it, indeed!

**Comment by rbisewski** [comment]
Yeah, I think cloudhead is right with regards to resolving the `~`.

I looked into ways of handling that when it was implemented and the dirs::BaseDirs crate seemed to be best choice since it makes gathering OS-wide / user-wide environment paths fairly easy and safe.

That said, I think implementing relative paths shouldn't be too hard, and I see that even std::path::Path supports an [official alias](https://doc.rust-lang.org/std/path/struct.Path.html#method.canonicalize) to the canonicalize function as well.

I'll make an attempt at this in a branch later tonight.

**Comment by roman-holovin** [comment]
Oh, I see. I was confused because documentation mentions that `canonicalize` uses `realpath` to expand paths on Unixes and I tried it in the shell and it worked. I missed the fact that shell expansion happens before command execution. Good to know, thanks.

**Comment by rbisewski** [comment]
Canonicalizing the paths required a bit of a rethink of the path parsing logic function, but I have made a PR that (hopefully) handles this well enough.

**Comment by rbisewski** [comment]
@cloudhead since this is merged I think this issue could be closed, whenever you have time :)
